### ISSUE TITLE
README should include information on what works and what doesn't

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-fat#70]
e.g., that [`format` can only make FAT16 filesystems](https://github.com/mirage/ocaml-fat/blob/master/src/fat_boot_sector.ml#L166), whether VFAT is implemented, what the user can expect to work and not work when writing to the filesystem, etc.

**Comment by djs55** [comment]
This is a good idea, I'll try to take care of it now (almost 3 years later!)
